### ISSUE TITLE
Resources running but dumpsters not working

### ISSUE THREAD

**Issue by SirDoodlesNY** [dann-5m/labrp_dumpster#1]
This is for QBCore, right?
And all we need to do is place the folder into our resources and ensure it in our server config?

I completed all that and it does not seem to be working for me either. 

I can see that the resources started in my counsel but when I go up to a dumpster I can't interact with it.

**Comment by dann-5m** [comment]
No this is for ESX

**Comment by SirDoodlesNY** [comment]
Okay, thanks. Now I see why this was not working for me.
